#!/usr/bin/env bash
# installer/test/service-unit.sh — is the systemd unit the installer writes a
# valid unit, and does it keep an unattended station coming back?
#
# Nothing checked this file. It is generated by a heredoc in
# installer/lib/65-service.sh, it is ~120 lines of directives, and a typo in a
# key name is silent: systemd logs "Unknown key name 'X', ignoring" into the
# journal at load time and starts the service anyway with that hardening,
# resource limit or restart rule simply absent. On a box in a field nobody
# reads that line. `systemd-analyze verify` reports it, and — verified here —
# still exits 0, so this test greps the output rather than trusting the status.
#
# The behavioural half is the restart policy. The unit carried:
#
#     StartLimitBurst=5
#     StartLimitIntervalSec=300
#
# which marks the unit **failed** after five restarts in five minutes and stops
# trying. The comment justified it as leaving the station down "for operator
# review (visible in the web UI's health page once the service comes back)" —
# circular, since the web UI is this service. Five restarts at RestartSec=10 is
# under a minute, so every self-clearing cause reached it: an external data
# disk that mounts late, a port the previous process still holds, a card that
# needs a second read. Each recovers on its own; none recovers from a unit
# systemd has given up on.
#
# Usage: installer/test/service-unit.sh
# Needs bash + coreutils; the validity checks additionally need
# systemd-analyze, and say so plainly when it is absent rather than passing.

set -uo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
FAILED=0

pass() { printf '  PASS  %s\n' "$*"; }
fail() { printf '  FAIL  %s\n' "$*"; FAILED=1; }

WORK="$(mktemp -d)"
trap 'rm -rf "${WORK}"' EXIT

UNIT="${WORK}/birdnet-behavior.service"

# Generate the unit with the real install_service, from the real module.
(
    set -euo pipefail
    # shellcheck disable=SC1090
    source <(sed -n '/^install_service()/,/^}/p' "${REPO_ROOT}/installer/lib/65-service.sh")

    info()    { :; }
    success() { :; }
    warn()    { :; }
    has_systemd() { return 1; }   # write the unit, do not touch systemctl

    # shellcheck disable=SC2034  # read by the sourced install_service
    SERVICE_FILE="${UNIT}"
    # shellcheck disable=SC2034
    REPO="tomtom215/BirdNet-Behavior"
    # shellcheck disable=SC2034
    SERVICE_USER="birdnet"
    # shellcheck disable=SC2034
    HELP_DIR="/usr/local/share/birdnet-behavior/help"
    # shellcheck disable=SC2034
    STREAM_DIR="/tmp/birdnet-stream"
    # shellcheck disable=SC2034
    INSTALL_DIR="/usr/local/bin"
    # shellcheck disable=SC2034
    BINARY_NAME="birdnet-behavior"
    # shellcheck disable=SC2034
    CONFIG_FILE="/etc/birdnet/birdnet.conf"
    # shellcheck disable=SC2034
    CONFIG_DIR="/etc/birdnet"
    # shellcheck disable=SC2034
    LISTEN_ADDR="0.0.0.0:8502"
    # shellcheck disable=SC2034
    IMAGE_CACHE_DIR="/home/birdnet/BirdNet-Behavior/image_cache"
    # shellcheck disable=SC2034
    DATA_DIR="/home/birdnet/BirdNet-Behavior"

    install_service
) >/dev/null 2>&1

if [ ! -s "${UNIT}" ]; then
    fail "install_service produced no unit file"
    echo "service-unit: FAILURES"
    exit 1
fi
pass "install_service wrote a unit"

echo "=== 1. every directive in the unit is one systemd recognises ==="
if command -v systemd-analyze >/dev/null 2>&1; then
    # `verify` wants a unit whose name it can resolve; run it on the file path.
    OUT="$(systemd-analyze verify "${UNIT}" 2>&1)"
    if grep -q "Unknown key name" <<<"${OUT}"; then
        fail "the unit contains directives systemd does not know:"
        grep "Unknown key name" <<<"${OUT}" | sed 's/^/        /'
    else
        pass "no unknown key names"
    fi
    # Anything else verify complains about is worth seeing, except the
    # unavoidable "does not exist" for paths that are not on this machine.
    if grep -Ev "Unknown key name|does not exist|not found|Failed to (open|resolve)" <<<"${OUT}" \
        | grep -q "[^[:space:]]"; then
        printf '  NOTE  systemd-analyze also said:\n'
        grep -Ev "Unknown key name|does not exist|not found|Failed to (open|resolve)" <<<"${OUT}" \
            | sed 's/^/        /'
    fi
else
    fail "systemd-analyze is not installed, so unit validity was NOT checked. \
This is a gap, not a pass — install systemd (Debian/Ubuntu: apt install systemd) \
or run this on a host that has it."
fi

echo
echo "=== 2. an unattended station is never permanently given up on ==="
# The whole point: no combination of directives may leave the unit failed and
# not retrying.
burst="$(grep -E '^StartLimitBurst=' "${UNIT}" | tail -1 | cut -d= -f2)"
interval="$(grep -E '^StartLimitIntervalSec=' "${UNIT}" | tail -1 | cut -d= -f2)"

if [ "${interval:-}" = "0" ]; then
    pass "StartLimitIntervalSec=0 — the rate limit is off, so the unit is never failed for retrying"
elif [ -z "${burst}" ] && [ -z "${interval}" ]; then
    fail "neither StartLimitBurst nor StartLimitIntervalSec is set, so systemd's \
default (5 starts / 10 s) applies and an unattended station can still be given up on"
else
    fail "StartLimitBurst=${burst:-<unset>} StartLimitIntervalSec=${interval:-<unset>} — \
a start rate limit is in force. After that many restarts systemd marks the unit \
failed and stops trying, and the only thing that would show an operator this \
happened is the web UI, which is this service."
fi

if grep -qE '^Restart=always' "${UNIT}"; then
    pass "Restart=always"
else
    fail "Restart= is not 'always'"
fi

echo
echo "=== 3. the tight-loop concern the rate limit was there for is handled ==="
# Removing the limit without backoff would trade one defect for another: a
# permanently broken install hammering every 10 s forever.
if grep -qE '^RestartSteps=' "${UNIT}" && grep -qE '^RestartMaxDelaySec=' "${UNIT}"; then
    maxdelay="$(grep -E '^RestartMaxDelaySec=' "${UNIT}" | tail -1 | cut -d= -f2)"
    pass "restart backoff is configured (up to ${maxdelay}s between attempts)"
else
    fail "no RestartSteps=/RestartMaxDelaySec= — without the rate limit and \
without backoff, a broken install retries every RestartSec forever"
fi

echo
echo "=== 4. the service waits for the filesystem its data lives on ==="
if grep -qE '^RequiresMountsFor=' "${UNIT}"; then
    pass "RequiresMountsFor= is set for the data directory"
else
    fail "no RequiresMountsFor= — with the data dir on an external disk, systemd \
starts the service against an empty mount point and the doctor preflight fails \
on an unwritable recordings directory"
fi

echo
echo "=== 5. the hardening that was deliberately chosen is still there ==="
# Not a style check: each of these was added for a reason recorded in
# 65-service.sh, and a heredoc is easy to edit carelessly.
for directive in \
    "Type=notify" \
    "WatchdogSec=" \
    "NoNewPrivileges=yes" \
    "ProtectSystem=strict" \
    "PrivateTmp=yes" \
    "CapabilityBoundingSet=" \
    "MemoryMax=" \
    "OOMPolicy=stop" \
    "DeviceAllow=char-alsa rw" \
    "SupplementaryGroups=audio"
do
    if grep -qF -- "${directive}" "${UNIT}"; then
        pass "${directive}"
    else
        fail "${directive} is missing from the generated unit"
    fi
done

echo
echo "=== 6. counterpart: the checks above can actually fail ==="
# Without this, section 5 is "grep found some strings" and sections 2-4 are
# satisfied by any unit at all.
BROKEN="${WORK}/broken.service"
sed -e 's/^StartLimitIntervalSec=0/StartLimitIntervalSec=300\nStartLimitBurst=5/' \
    -e '/^RestartSteps=/d' -e '/^RestartMaxDelaySec=/d' \
    -e '/^RequiresMountsFor=/d' \
    -e 's/^NoNewPrivileges=yes/NoNewPrivilages=yes/' \
    "${UNIT}" >"${BROKEN}"

if grep -qE '^StartLimitBurst=5' "${BROKEN}"; then
    pass "the mutated unit really does carry a start rate limit"
else
    fail "the mutation did not apply — section 6 proves nothing"
fi
if ! grep -qE '^RequiresMountsFor=' "${BROKEN}" && ! grep -qE '^RestartSteps=' "${BROKEN}"; then
    pass "the mutated unit really is missing the mount wait and the backoff"
else
    fail "the mutation did not apply"
fi
if command -v systemd-analyze >/dev/null 2>&1; then
    BROKEN_OUT="$(systemd-analyze verify "${BROKEN}" 2>&1)"
    if grep -q "NoNewPrivilages" <<<"${BROKEN_OUT}"; then
        pass "systemd-analyze catches a misspelled directive (which exits 0, hence the grep)"
    else
        fail "systemd-analyze did NOT report a misspelled directive — section 1 is not checking anything. It said:"
        sed 's/^/        /' <<<"${BROKEN_OUT}"
    fi
fi

echo
echo "=== 7. the zram unit does not switch off the operator's real swap ==="
# setup_zram writes a second unit, and its ExecStop began `swapoff -a` —
# documented as "disable all swaps from /proc/swaps", i.e. every swap on the
# machine. Raspberry Pi OS enables dphys-swapfile by default, so stopping this
# unit turned off the operator's real swap on exactly the low-RAM boards it
# exists to help. It also piped device paths into `rmmod`, which takes a module
# name, so the unload failed on every run behind a `|| true`.
ZRAM="${WORK}/zram-swap.service"
(
    set -euo pipefail
    # shellcheck disable=SC2034  # expanded by the module's own heredoc below
    zram_size=1073741824
    # The heredoc from the real module, rendered with a real size.
    eval "cat > \"${ZRAM}\" << EOF
$(sed -n '/^\[Unit\]$/,/^WantedBy=multi-user.target$/p' \
    <(sed -n '/local zram_service=/,/^EOF$/p' "${REPO_ROOT}/installer/lib/82-zram.sh"))
EOF"
) >/dev/null 2>&1

if [ ! -s "${ZRAM}" ]; then
    fail "could not render the zram unit from 82-zram.sh — this section checked nothing"
else
    execstop="$(grep -E '^ExecStop=' "${ZRAM}" || true)"
    if grep -qE '(^|[^-])swapoff[[:space:]]+(-a|--all)' <<<"${execstop}"; then
        fail "ExecStop still runs 'swapoff -a', which disables every swap on the machine \
including dphys-swapfile: ${execstop}"
    else
        pass "ExecStop does not disable all swap"
    fi
    if grep -qE 'swapoff .*(/dev/zram|\$d)' <<<"${execstop}"; then
        pass "ExecStop targets zram devices specifically"
    else
        fail "ExecStop no longer swaps off the zram devices it created: ${execstop}"
    fi
    if grep -qE 'xargs[^|]*rmmod' <<<"${execstop}"; then
        fail "ExecStop pipes device paths into rmmod, which takes a module name: ${execstop}"
    else
        pass "the module is unloaded by name, not by device path"
    fi
    if command -v systemd-analyze >/dev/null 2>&1; then
        ZOUT="$(systemd-analyze verify "${ZRAM}" 2>&1)"
        if grep -q "Unknown key name" <<<"${ZOUT}"; then
            fail "the zram unit contains directives systemd does not know:"
            grep "Unknown key name" <<<"${ZOUT}" | sed 's/^/        /'
        else
            pass "the zram unit has no unknown key names"
        fi
    fi
fi

echo
if [ "${FAILED}" -eq 0 ]; then
    echo "service-unit: all pass"
else
    echo "service-unit: FAILURES"
fi
exit "${FAILED}"
