# ---------------------------------------------------------------------------
# Write the default configuration file
# ---------------------------------------------------------------------------

write_config() {
    if [ -f "${CONFIG_FILE}" ]; then
        warn "Config file already exists at ${CONFIG_FILE} — skipping."
        # Upgrade from a version that left the config world-readable: tighten it
        # without touching the user's settings.
        chown "root:${SERVICE_USER}" "${CONFIG_FILE}" 2>/dev/null || true
        chmod 0640 "${CONFIG_FILE}"
        return
    fi

    # Bake interactive / auto-detected answers in; otherwise keep the commented
    # examples. Heredoc expansion is single-pass, so a value containing $ or
    # backticks (e.g. an RTSP URL with credentials) is written literally.
    local alsa_line="# ALSA_CARD=plughw:1,0"
    local rtsp_line="# RTSP_URL=rtsp://camera.local:554/stream"
    local lat_line="# LATITUDE=51.5074"
    local lon_line="# LONGITUDE=-0.1278"
    [ -n "${ALSA_CARD_VALUE}" ] && alsa_line="ALSA_CARD=${ALSA_CARD_VALUE}"
    [ -n "${RTSP_URL_VALUE}" ]  && rtsp_line="RTSP_URL=${RTSP_URL_VALUE}"
    [ -n "${LATITUDE_VALUE}" ]  && lat_line="LATITUDE=${LATITUDE_VALUE}"
    [ -n "${LONGITUDE_VALUE}" ] && lon_line="LONGITUDE=${LONGITUDE_VALUE}"
    local caddy_user_line="# CADDY_USER=admin"
    local caddy_pwd_line="# CADDY_PWD=change-me-to-a-strong-password"
    [ -n "${CADDY_USER_VALUE}" ] && caddy_user_line="CADDY_USER=${CADDY_USER_VALUE}"
    [ -n "${CADDY_PWD_VALUE}" ]  && caddy_pwd_line="CADDY_PWD=${CADDY_PWD_VALUE}"
    # Persist the bind address so `install.sh repair`/`update` keep it (the
    # installer reads BIRDNET_LISTEN back from here on re-run).
    local listen_line="BIRDNET_LISTEN=${LISTEN_ADDR}"
    # The geomodel is optional and its download is non-fatal, so the two
    # settings are only written live when both files actually landed. Writing
    # them unconditionally would point a fresh station at paths that do not
    # exist, and `--doctor` would then report FAIL on an install that had merely
    # declined an optional download.
    local geo_model_line="# METADATA_MODEL_PATH="
    local geo_labels_line="# METADATA_LABELS_PATH="
    if [ "${GEOMODEL_INSTALLED:-0}" = "1" ]; then
        geo_model_line="METADATA_MODEL_PATH=${MODEL_DIR}/${GEOMODEL_FILE}"
        geo_labels_line="METADATA_LABELS_PATH=${MODEL_DIR}/${GEOMODEL_LABELS_FILE}"
    fi

    info "Writing default config to ${CONFIG_FILE}…"
    cat > "${CONFIG_FILE}" <<EOF
# BirdNet-Behavior configuration
# Generated by install.sh on $(date -u +"%Y-%m-%d %H:%M UTC")
#
# Edit this file then restart: sudo systemctl restart birdnet-behavior

# --- Paths ---
DB_PATH=${DB_PATH}
RECS_DIR=${RECS_DIR}
IMAGE_CACHE_DIR=${IMAGE_CACHE_DIR}

# --- Model (BirdNET+ V3.0, downloaded automatically by installer) ---
MODEL_PATH=${MODEL_DIR}/${MODEL_FILE}
LABELS_PATH=${MODEL_DIR}/${LABELS_FILE}

# --- Audio source ---
# Use one of: ALSA microphone, RTSP stream, or an existing recordings directory.
${alsa_line}
${rtsp_line}
# Multiple RTSP cameras: comma-separated. Each becomes its own capture stream
# (filenames/metrics prefixed RTSP_1, RTSP_2, …). Overrides RTSP_URL when set.
# RTSP_URLS=rtsp://cam1:554/stream,rtsp://cam2:554/stream

# --- Location (used for species frequency filtering and BirdWeather) ---
${lat_line}
${lon_line}
# RECORDING_SCHEDULE=all-day   # all-day | solar | fixed:HH:MM-HH:MM
#                              # solar records sunrise-to-sunset and needs the
#                              # coordinates above. Fixed hours are evaluated in
#                              # UTC, not local time. Also settable in the web UI
#                              # under Settings -> Location & Recording Schedule.

# --- Detection ---
# CONFIDENCE=0.75          # 0.0–1.0, default 0.75 (detections below this are discarded).
#                          # The setup wizard asks for this on first login; note
#                          # that unlike SF_THRESH, 0 does not mean "disabled" —
#                          # it records every window as a detection.
# SENSITIVITY=1.25         # 0.5–1.5, default 1.25 (V2.4 models only; V3.0 ignores it)
# OVERLAP=0.0              # seconds of 3 s analysis window overlap
# DATABASE_LANG=en

# --- Logging ---
# LOG_LEVEL=info           # trace|debug|info|warn|error|off (RUST_LOG wins)
# LOG_MODULES=             # per subsystem, e.g. audio=debug,web=warn
#                          # names: audio detection web db integrations analytics

# --- Species occurrence filtering ---
# Drops species that do not occur near this station at this time of year. Needs
# all three of the following; the installer fetches the last two for you, and
# the two settings below are live when it succeeded, commented out when it did
# not.
#   1. station coordinates (set above, or on the dashboard)
#   2. METADATA_MODEL_PATH   — the BirdNET geomodel (ONNX)
#   3. METADATA_LABELS_PATH  — that model's own label file
# The geomodel scores a different species list from the classifier (12 012
# against 11 560), so the label file is what maps one onto the other; omit it
# only for a metadata model indexed identically to the classifier, which the
# station verifies at startup and refuses if it does not hold.
# Run \`birdnet-behavior --doctor\` to see which of the three is missing.
${geo_model_line}
${geo_labels_line}
# SF_THRESH=0.03           # occurrence threshold; no effect while the filter is off

# --- Disk management ---
# MAX_FILES_SPECIES=0      # 0 = keep all recordings per species; set e.g. 100 to cap
# DISK_PURGE_THRESHOLD=95
# Raw capture segments land in the RAM-backed stream dir (--watch-dir, default
# /tmp/birdnet-stream) and are drained once the detector has processed them, so
# the tmpfs cannot fill. Tune the rolling buffer if needed:
# STREAM_RETENTION_SECS=600  # delete processed raw segments older than this (0 = off)
# STREAM_MAX_MB=512          # hard cap on the stream dir; oldest segments drop first (0 = off)

# --- Notifications (Apprise) ---
# APPRISE_URL=http://localhost:8000

# --- BirdWeather ---
# BIRDWEATHER_TOKEN=your-token-here

# --- Site name shown in web UI ---
# SITENAME=My Bird Station

# --- Web dashboard bind address ---
# Default 0.0.0.0:8502 = reachable from other devices on your LAN. Viewing the
# dashboard is open; the /admin panel (settings, software update) is gated by
# CADDY_PWD below. To restrict the WHOLE dashboard to this device, set
# 127.0.0.1:8502, then apply it with:  sudo bash install.sh repair
${listen_line}

# --- Admin authentication (CADDY_PWD) ---
# The /admin panel can change settings, trigger backups, and update the
# software, so it requires a sign-in through the dashboard's login form.
# A fresh install sets a strong CADDY_PWD automatically; change it here any
# time, then apply it with:  sudo bash install.sh repair
#
# Sign in with the username "admin" — that is the account the dashboard seeds,
# and it is the only one that exists until you create more in the admin panel.
# CADDY_USER below does NOT rename it: the login form reads CADDY_USER from the
# process environment only, and this unit sets no EnvironmentFile, so on a
# bare-metal install it has no effect. It is honoured under Docker, where the
# environment does reach the process.
#
# Clearing CADDY_PWD leaves /admin OPEN to anyone who can reach the dashboard.
${caddy_user_line}
${caddy_pwd_line}
EOF
    # The config can hold secrets (CADDY_PWD, BIRDWEATHER_TOKEN), so keep it
    # readable by the service's group but never world-readable. Root owns it so
    # the non-root service can read but not rewrite its own config.
    chown "root:${SERVICE_USER}" "${CONFIG_FILE}"
    chmod 0640 "${CONFIG_FILE}"
    success "Default config written — edit ${CONFIG_FILE} to configure your station."
}
