//! `offsite::sigv4` against a reference implementation, not against a reading
//! of the specification.
//!
//! # Provenance of the vectors
//!
//! `sigv4_vectors.json` is generated by `sigv4_vectors.py` (beside it) from
//! **botocore**, the signing code inside the AWS CLI and boto3 — an independent
//! implementation exercised by every AWS user in the world. The generator pins
//! `botocore`'s clock and otherwise runs its own code path unchanged.
//!
//! The chain is anchored at the top: the `aws_published_get_object` vector is
//! AWS's own "Example: GET Object" from the S3 documentation, whose signature
//! `f0e8bdb…6036bdb41` is printed there, and `botocore` reproduces it byte for
//! byte. That is what makes `botocore` usable as the reference for the six
//! vectors AWS does not publish.
//!
//! # Why a table rather than assertions written by hand
//!
//! Because a signature is a hash: it is either exactly right or completely
//! wrong, and there is nothing to reason about in between. Hand-written
//! expectations here would be transcriptions of whatever this implementation
//! happened to produce on the day, which proves only that it is deterministic.
//!
//! To regenerate after an intentional change:
//!
//! ```text
//! pip install --target /tmp/boto `botocore`
//! python3 crates/birdnet-integrations/tests/sigv4_vectors.py /tmp/boto \
//!     > crates/birdnet-integrations/tests/sigv4_vectors.json
//! ```

use birdnet_integrations::offsite::sigv4::{self, Credentials, Request};

/// The example credentials the AWS documentation uses. Not a secret — they
/// appear verbatim in AWS's own published signing examples.
const ACCESS_KEY: &str = "AKIAIOSFODNN7EXAMPLE";
const SECRET_KEY: &str = "wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY";

#[derive(serde::Deserialize)]
struct Vector {
    name: String,
    method: String,
    host: String,
    path: String,
    #[serde(default)]
    query: std::collections::BTreeMap<String, String>,
    #[serde(default)]
    extra_headers: std::collections::BTreeMap<String, String>,
    region: String,
    timestamp: String,
    payload_sha256: String,
    canonical_request: String,
    authorization: String,
}

fn vectors() -> Vec<Vector> {
    let raw = include_str!("sigv4_vectors.json");
    serde_json::from_str(raw).expect("sigv4_vectors.json must parse")
}

#[test]
fn every_vector_signs_identically_to_botocore() {
    let creds = Credentials {
        access_key: ACCESS_KEY.to_owned(),
        secret_key: SECRET_KEY.to_owned(),
    };

    let all = vectors();
    assert!(
        all.len() >= 7,
        "the vector file lost entries — it should carry the AWS-published \
         example plus the six shapes this target actually sends; got {}",
        all.len()
    );
    assert!(
        all.iter().any(|v| v.name == "aws_published_get_object"),
        "the vector anchored to AWS's own published signature is missing; \
         without it botocore is an unchecked reference"
    );

    for v in all {
        let query: Vec<(String, String)> = v
            .query
            .iter()
            .map(|(k, val)| (k.clone(), val.clone()))
            .collect();
        let extra: Vec<(String, String)> = v
            .extra_headers
            .iter()
            .map(|(k, val)| (k.to_ascii_lowercase(), val.clone()))
            .collect();

        let signed = sigv4::sign(
            &creds,
            &Request {
                method: &v.method,
                host: &v.host,
                path: &v.path,
                query: &query,
                payload_sha256: &v.payload_sha256,
                extra_headers: &extra,
                region: &v.region,
                timestamp: &v.timestamp,
            },
        );

        // The canonical request is compared as well as the signature. Both
        // being wrong the same way is impossible — the signature is a hash of
        // the canonical request — but when the signature differs, the canonical
        // request is what says *where*, and a diff of two strings is a far
        // better failure message than a diff of two hashes.
        assert_eq!(
            signed.canonical_request, v.canonical_request,
            "canonical request differs for `{}`",
            v.name
        );
        assert_eq!(
            signed.authorization, v.authorization,
            "Authorization header differs for `{}`",
            v.name
        );
    }
}

#[test]
fn the_vector_table_actually_covers_the_shapes_it_claims_to() {
    // A table of seven identical GETs would pass the gate above and check
    // nothing. Pin the coverage: every method the backup target uses, both
    // addressing styles, a host with a port, a query string, and a key that
    // needs percent-encoding.
    let all = vectors();
    let has = |f: &dyn Fn(&Vector) -> bool, what: &str| {
        assert!(all.iter().any(f), "no vector covers {what}");
    };
    has(&|v| v.method == "PUT", "PUT (uploading a backup)");
    has(&|v| v.method == "GET", "GET (listing)");
    has(&|v| v.method == "DELETE", "DELETE (retention)");
    has(&|v| v.host.contains(':'), "a host carrying a port");
    has(&|v| !v.query.is_empty(), "a query string");
    has(
        &|v| v.query.len() > 1,
        "more than one query parameter, which is what makes the sort observable",
    );
    has(
        &|v| v.path.contains(' ') || v.path.contains('+'),
        "a key needing percent-encoding",
    );
    has(
        &|v| v.host.starts_with("examplebucket."),
        "virtual-host-style addressing",
    );
    has(
        &|v| !v.host.starts_with("examplebucket.") && v.path.matches('/').count() >= 2,
        "path-style addressing",
    );
    has(
        &|v| v.payload_sha256 != sigv4::EMPTY_PAYLOAD_SHA256,
        "a request with a body, so the payload hash is not always the constant",
    );
    has(
        &|v| v.region != "us-east-1",
        "a region other than us-east-1",
    );
    has(
        &|v| !v.extra_headers.is_empty(),
        "an extra signed header beyond the three that are always present",
    );
}
